# Generated by Django 4.2.30 on 2026-06-18 14:50

import apps.website.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_seller_product_seller_and_more'),
        ('authx', '0008_userprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.website.models.website_upload_to)),
                ('ebook_file', models.FileField(blank=True, null=True, upload_to=apps.website.models.website_upload_to)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to='authx.firm')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebooks', to='ecommerce.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('amount_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='website.ebook')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_purchases', to='authx.firm')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ebook_sales', to='ecommerce.seller')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.website.models.website_upload_to)),
                ('verification_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='authx.firm')),
            ],
            options={
                'ordering': ['sort_order', '-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='authx.firm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=apps.website.models.website_upload_to)),
                ('author_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='website.articlecategory')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='authx.firm')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ebook',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_ebook_slug_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_article_category_slug_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_article_slug_per_firm'),
        ),
    ]
