# Generated by Django 4.2.30 on 2026-06-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_seller_product_seller_and_more'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='related_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_editions', to='ecommerce.product'),
        ),
    ]
