# Generated by Django 4.2.30 on 2026-06-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ebook_related_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='related_book',
        ),
    ]
