# Generated by Django 4.2.30 on 2026-06-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_ebook_related_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='certification',
            name='credential_id',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='expires_on',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issued_on',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='verification_url',
        ),
    ]
