# Generated by Django 4.2.30 on 2026-06-20 09:17

import apps.website.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('casetypes', '0002_remove_casetype_uniq_case_type_name_per_firm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authx', '0008_userprofile_profile_image'),
        ('website', '0004_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('how_we_help', models.TextField()),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(default='Sharjah', max_length=120)),
                ('languages', models.CharField(blank=True, default='Arabic, English', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.website.models.website_upload_to)),
                ('supports_online', models.BooleanField(default=True)),
                ('supports_physical', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_services', to='casetypes.casetype')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_services', to='authx.firm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerOffDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_off_days', to='authx.firm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='off_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LawyerAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_availability', to='authx.firm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lawyer_id', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('appointment_type', models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('amount_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('meeting_provider', models.CharField(blank=True, max_length=50)),
                ('meeting_url', models.URLField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authx.firm')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_appointments', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='website.legalservice')),
            ],
            options={
                'ordering': ['-appointment_date', '-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='legalservice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_legal_service_slug_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='lawyeroffday',
            constraint=models.UniqueConstraint(fields=('firm', 'lawyer', 'date', 'start_time'), name='uniq_lawyer_off_period'),
        ),
        migrations.AddConstraint(
            model_name='lawyeravailability',
            constraint=models.UniqueConstraint(fields=('firm', 'lawyer', 'weekday', 'start_time'), name='uniq_lawyer_availability_window'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['lawyer', 'appointment_date', 'start_time'], name='website_app_lawyer__ae0a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['firm', 'status'], name='website_app_firm_id_40774a_idx'),
        ),
    ]
