# Generated by Django 4.2.30 on 2026-06-21 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0008_userprofile_profile_image'),
        ('website', '0005_legalservice_lawyeroffday_lawyeravailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='website.appointment')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reviews', to='authx.firm')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='website.legalservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentreview',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='appointment_review_rating_1_to_5'),
        ),
    ]
