# Generated by Django 4.2.30 on 2026-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_appointmentreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreview',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Marks demonstration content that must not be represented as a verified client review.'),
        ),
    ]
