# Generated by Django 4.2.28 on 2026-02-07 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_firmcasecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='cases_assigned_multi', to=settings.AUTH_USER_MODEL),
        ),
    ]
