# Generated by Django 4.2.28 on 2026-02-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assigned_users',
        ),
    ]
