# Generated by Django 4.2.28 on 2026-02-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casetypes', '0002_remove_casetype_uniq_case_type_name_per_firm_and_more'),
        ('cases', '0004_remove_case_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='casetypes.casetype'),
        ),
    ]
