# Generated by Django 4.2.28 on 2026-02-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='tasks_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
