# Generated by Django 4.2.28 on 2026-02-24 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0009_case_pending_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tasks_generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_tasks_generated', to=settings.AUTH_USER_MODEL),
        ),
    ]
