# Generated by Django 4.2.28 on 2026-02-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetypes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='casetype',
            name='uniq_case_type_name_per_firm',
        ),
        migrations.RemoveConstraint(
            model_name='casetype',
            name='uniq_case_type_code_per_firm',
        ),
        migrations.AddConstraint(
            model_name='casetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('firm', 'name'), name='uniq_case_type_name_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='casetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('code__isnull', True), _negated=True)), fields=('firm', 'code'), name='uniq_case_type_code_per_firm'),
        ),
    ]
