# Generated by Django 4.2.28 on 2026-03-28 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatx', '0002_group_features'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroommember',
            name='chatx_chatroommember_room_user_uniq',
        ),
        migrations.RenameIndex(
            model_name='chatattachment',
            new_name='chatx_chata_firm_id_3cdc0b_idx',
            old_name='chatx_chat_att_fir_mes_1e3b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatx_chatm_firm_id_f99340_idx',
            old_name='chatx_chat_mes_fir_roo_d53e93_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatx_chatm_room_id_776768_idx',
            old_name='chatx_chat_mes_room_id_6d9c07_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chatx_chatm_firm_id_d8e833_idx',
            old_name='chatx_chat_mes_firm_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chatx_chatr_firm_id_1d2540_idx',
            old_name='chatx_chat_room_fir_07b6db_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chatx_chatr_firm_id_591276_idx',
            old_name='chatx_chat_room_firm_type_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroom',
            new_name='chatx_chatr_firm_id_2a8b82_idx',
            old_name='chatx_chat_room_firm_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chatx_chatr_firm_id_9d7afe_idx',
            old_name='chatx_chat_room_fir_roo_c7aeb6_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chatx_chatr_firm_id_bc87ed_idx',
            old_name='chatx_chat_room_fir_use_c8c2dc_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chatx_chatr_room_id_815d26_idx',
            old_name='chatx_chat_room_room_active_idx',
        ),
        migrations.RenameIndex(
            model_name='chatroommember',
            new_name='chatx_chatr_user_id_33e6b1_idx',
            old_name='chatx_chat_room_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='chatx_messa_firm_id_05eb1b_idx',
            old_name='chatx_mess_rece_fir_use_324123_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chatroommember',
            unique_together={('room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereceipt',
            unique_together={('message', 'user')},
        ),
    ]
