# Generated by Django 4.2.28 on 2026-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hearings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casehearing',
            new_name='case_hearin_firm_id_0f3375_idx',
            old_name='hearings_firm_case_idx',
        ),
        migrations.RenameIndex(
            model_name='casehearing',
            new_name='case_hearin_firm_id_7bc214_idx',
            old_name='hearings_firm_start_idx',
        ),
        migrations.RenameIndex(
            model_name='casehearing',
            new_name='case_hearin_firm_id_1b62f7_idx',
            old_name='hearings_status_idx',
        ),
    ]
