# Generated by Django 4.2.28 on 2026-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
