# Generated by Django 4.2.28 on 2026-02-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0005_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='authx.firm'),
        ),
    ]
