# Generated by Django 4.2.28 on 2026-02-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0006_userprofile_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
