# Generated by Django 4.2.28 on 2026-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_firm_id_ddb9e3_idx',
            old_name='auditlog_firm_ca_1ecf57_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_firm_id_06de30_idx',
            old_name='auditlog_firm_en_c528e9_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_firm_id_2e6166_idx',
            old_name='auditlog_firm_ac_722479_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_firm_id_045f4f_idx',
            old_name='auditlog_firm_ac_825bfb_idx',
        ),
    ]
