# Generated by Django 4.2.28 on 2026-02-26 07:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authx', '0007_firm_status_userprofile_must_change_password'),
        ('casetypes', '0002_remove_casetype_uniq_case_type_name_per_firm_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTypeFeePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_firm_id_5efadc_idx',
            old_name='billing_inv_firm_id_2999f3_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_firm_id_647e0b_idx',
            old_name='billing_inv_firm_id_2cfec1_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_firm_id_e95407_idx',
            old_name='billing_pay_firm_id_fab8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_firm_id_b3f411_idx',
            old_name='billing_pay_firm_id_e3a635_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='casetypefeepolicy',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_policies', to='casetypes.casetype'),
        ),
        migrations.AddField(
            model_name='casetypefeepolicy',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_type_fee_policies', to='authx.firm'),
        ),
        migrations.AddIndex(
            model_name='invoicelineitem',
            index=models.Index(fields=['invoice', 'created_at'], name='billing_inv_invoice_09e081_idx'),
        ),
        migrations.AddIndex(
            model_name='casetypefeepolicy',
            index=models.Index(fields=['firm', 'case_type'], name='billing_cas_firm_id_e094ab_idx'),
        ),
        migrations.AddIndex(
            model_name='casetypefeepolicy',
            index=models.Index(fields=['firm', 'is_active'], name='billing_cas_firm_id_d66c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='casetypefeepolicy',
            index=models.Index(fields=['firm', 'is_deleted'], name='billing_cas_firm_id_ff3e4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='casetypefeepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('firm', 'case_type'), name='uniq_case_type_fee_policy_per_firm_case_type'),
        ),
    ]
