# Generated by Django 4.2.28 on 2026-02-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authx', '0006_userprofile_firm'),
        ('casetypes', '0002_remove_casetype_uniq_case_type_name_per_firm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='casetypes.casetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_task_templates', to='authx.firm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTaskTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('default_status', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='TODO', max_length=15)),
                ('due_in_days', models.PositiveIntegerField(blank=True, null=True)),
                ('assign_to', models.CharField(choices=[('CASE_LEAD', 'Case Lead'), ('CASE_LAWYER', 'Case Lawyer'), ('CASE_PARALEGAL', 'Case Paralegal'), ('CASE_ACCOUNTANT', 'Case Accountant'), ('UNASSIGNED', 'Unassigned')], default='UNASSIGNED', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='task_templates.casetasktemplate')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='casetasktemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True), ('is_deleted', False)), fields=('firm', 'case_type'), name='uniq_default_task_template_per_case_type'),
        ),
    ]
