# Generated by Django 4.2.28 on 2026-02-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permission',
            new_name='rbac_permis_module_833fff_idx',
            old_name='rbac_permi_module_action_idx',
        ),
    ]
