# Generated by Django 4.2.28 on 2026-03-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifx', '0002_notification_outbox_and_v2_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifx_noti_recipie_14cea9_idx',
            old_name='notifx_notif_recipie_84a34a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifx_noti_recipie_842b93_idx',
            old_name='notifx_notif_recipie_44cad8_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifx_noti_firm_id_3a35e7_idx',
            old_name='notifx_notif_firm_id_3f7fed_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifx_noti_firm_id_2a5540_idx',
            old_name='notifx_notif_firm_id_7663f1_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notifx_noti_firm_id_59224d_idx',
            old_name='notifx_not_fir_use_is__734c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationoutbox',
            new_name='notifx_noti_status_ba4d15_idx',
            old_name='notifx_noti_status_cd0f47_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationoutbox',
            new_name='notifx_noti_firm_id_6c1913_idx',
            old_name='notifx_noti_firm_id_72e9f6_idx',
        ),
    ]
