# Generated by Django 4.2.28 on 2026-02-09 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0005_alter_case_case_type'),
        ('authx', '0006_userprofile_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='TODO', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authx.firm')),
                ('generated_from_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='task_templates.casetasktemplate')),
                ('generated_from_template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='task_templates.casetasktemplateitem')),
            ],
            options={
                'ordering': ['due_date', '-priority', '-created_at'],
                'indexes': [models.Index(fields=['firm', 'status', 'is_deleted'], name='tasks_caset_firm_id_028f34_idx'), models.Index(fields=['firm', 'assigned_to', 'status', 'is_deleted'], name='tasks_caset_firm_id_924de9_idx'), models.Index(fields=['firm', 'case', 'status', 'is_deleted'], name='tasks_caset_firm_id_f34864_idx'), models.Index(fields=['firm', 'due_date'], name='tasks_caset_firm_id_7bf0cf_idx')],
            },
        ),
    ]
