# Generated by Django 4.2.28 on 2026-02-27 07:12

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(max_length=512, upload_to=apps.documents.models.case_document_upload_to),
        ),
    ]
