# Generated by Django 4.2.28 on 2026-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='intakerequest',
            new_name='intake_inta_firm_id_810232_idx',
            old_name='intakerequ_firm_id_5611a3_idx',
        ),
        migrations.RenameIndex(
            model_name='intakerequest',
            new_name='intake_inta_firm_id_e45ce6_idx',
            old_name='intakerequ_firm_id_90b9e6_idx',
        ),
        migrations.RenameIndex(
            model_name='intakerequest',
            new_name='intake_inta_firm_id_c4af9c_idx',
            old_name='intakerequ_firm_id_c35505_idx',
        ),
        migrations.RenameIndex(
            model_name='intakerequest',
            new_name='intake_inta_firm_id_252bc3_idx',
            old_name='intakerequ_firm_id_3b88b3_idx',
        ),
        migrations.AlterField(
            model_name='intakerequest',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('WHATSAPP', 'WhatsApp'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='WEBSITE', max_length=20),
        ),
    ]
