# Generated by Django 4.2.28 on 2026-03-28 08:03

import apps.ecommerce.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authx', '0007_firm_status_userprofile_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONVERTED', 'Converted'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_categories', to='authx.firm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_collections', to='authx.firm')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('subtotal_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_amount_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount_aed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COD', 'Cash On Delivery'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COD', max_length=20)),
                ('shipping_method', models.CharField(max_length=120)),
                ('shipping_address', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_orders', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_orders', to='authx.firm')),
            ],
            options={
                'ordering': ['-placed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price_aed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_per_item', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sku', models.CharField(max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('track_inventory', models.BooleanField(default=True)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('shipping_required', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft'), ('UNLISTED', 'Unlisted')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ecommerce.category')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='ecommerce.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_products_created', to=settings.AUTH_USER_MODEL)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_products', to='authx.firm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_products_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=120)),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price_aed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('barcode', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('option_values', models.JSONField(blank=True, default=dict)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_product_variants', to='authx.firm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ecommerce.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_product_tags', to='authx.firm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ecommerce.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('FEATURE', 'Feature'), ('GALLERY', 'Gallery')], default='GALLERY', max_length=20)),
                ('image', models.FileField(max_length=512, upload_to=apps.ecommerce.models.product_media_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_product_media', to='authx.firm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ecommerce.product')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecommerce_product_media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ecommerce.product')),
            ],
            options={
                'ordering': ['key', 'value'],
            },
        ),
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_number', models.PositiveIntegerField(default=1001)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_order_sequence', to='authx.firm')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('variant_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(max_length=120)),
                ('price_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal_aed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ecommerce.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ecommerce.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerce.productvariant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='converted_to_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_carts', to='ecommerce.order'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_carts', to='authx.firm'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['firm', 'product', 'is_active'], name='ecommerce_p_firm_id_6834bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'sku'), name='uniq_ecom_variant_sku_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='producttag',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uniq_ecom_product_tag_name'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['firm', 'product', 'sort_order'], name='ecommerce_p_firm_id_8b6a02_idx'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'key', 'value'), name='uniq_ecom_product_attribute'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['firm', 'status', 'created_at'], name='ecommerce_p_firm_id_780446_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['firm', 'collection', 'status'], name='ecommerce_p_firm_id_d8f985_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['firm', 'category', 'status'], name='ecommerce_p_firm_id_e955be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['firm', 'is_featured', 'status'], name='ecommerce_p_firm_id_59cc41_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_ecom_product_slug_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'sku'), name='uniq_ecom_product_sku_per_firm'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firm', 'order_status', 'placed_at'], name='ecommerce_o_firm_id_7abb84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firm', 'payment_status', 'placed_at'], name='ecommerce_o_firm_id_1dbaae_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firm', 'customer', 'placed_at'], name='ecommerce_o_firm_id_9e1e44_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firm', 'order_number'], name='ecommerce_o_firm_id_8a961f_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['firm', 'is_active'], name='ecommerce_c_firm_id_fe9c68_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['firm', 'slug'], name='ecommerce_c_firm_id_901d1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_ecom_collection_slug_per_firm'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['firm', 'is_active'], name='ecommerce_c_firm_id_b92797_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['firm', 'slug'], name='ecommerce_c_firm_id_2879ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('firm', 'slug'), name='uniq_ecom_category_slug_per_firm'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant'), name='uniq_ecom_cart_line'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['firm', 'customer', 'status'], name='ecommerce_c_firm_id_2ce40e_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['firm', 'guest_token', 'status'], name='ecommerce_c_firm_id_4d1d39_idx'),
        ),
    ]
