# Generated by Django 4.2.28 on 2026-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
